[   .000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.0-139-generic (buildd@lcy01-amd64-006) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 (Ubuntu 4.4.0-139.165-generic 4.4.160)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-139-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Supporting XSAVE feature 0x01: 'x87 floating point registers
    0.000000] x86/fpu: Supporting XSAVE feature 0x02: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x04: 'AVX registers'
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000dffeffff] usable
[    0.000000] BIOS-e820: [mem 0x00000000dfff0000-0x00000000dfffffff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fee00000-0x00000000fee00fff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000041fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.5 present.
[    0.000000] Hypervisor detected: KVM
[    0.000000] e820: last_pfn = 0x420000 max_arch_pfn = 0x400000000
[    000000] MTRR: Disabled
[    0.000000] x86/PAT: MTRRs disabled, skipping PAT initialization too.
[    0.000000] CPU MTRRs all blank - virtualized system.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] e820: last_pfn = 0xdfff0 max_arch_pfn = 0x400000000
[    0.000000] found SMP MP-table at [mem 0x0009fff0-0x0009ffff] mapped at [ffff88000009fff0]
[    0.000000] Scanning 1 areas for low memory corruption
[    0.000000] RAMDISK: [mem 0x3630c000-0x3717dfff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x00000000000E0000 000024 (v02 VBOX  )
[    0.000000] ACPI: XSDT 0x00000000DFFF0030 00003C (v01 VBOX   VBOXXSDT 00000001 ASL  00000061)
[    0.000000] ACPI: FACP 0x00000000DFFF00F0 0000F4 (v04 VBOX   VBOXFACP 00000001 ASL  00000061)
[    0.000000] ACPI: DSDT 0x00000000DFFF0480 0021FF (v02 VBOX   VBOXBIOS 00000002 INTL 20100528)
[    0.000000] ACPI: FACS 0x00000000DFFF0200 000040
[    0.000000] ACPI: FACS 0x00000000DFFF0200 000040
[    0.000000] ACPI: APIC 0x00000000DFFF0240 00006C (v02 VBOX   VBOXAPIC 00000001 ASL  00000061)
[    0.000000] ACPI: SSDT 0x00000000DFFF02B0 0001CC (v01 VBOX   VBOXCPUT 00000002 INTL 20100528)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at [mem 0x0000000000000000-0x000000041fffffff]
[    0.000000] NODE_DATA(0) allocated [mem 0x41ffed000-0x41fff1fff]
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 4:1ffe5001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 3920166537 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x000000041fffffff]
[    0.000000]   Device   empty
[    0.000000] Movable zone start for ech node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x00000000dffeffff]
[    0.000000]   node   0: [mem 0x0000000100000000-0x000000041fffffff]
[    0.000000] Initmem setup node 0 [mm x0000000000001000-0x000000041fffffff]
[    0.000000] ACPI: PM-Timer IO Port: 0x4008
[    0.000000] IOAPIC[0]: apic_id 4, version 32, address 0xfec00000, GSI 0-
[   .000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] smpboot: Allowing 4 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
[    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000effff]
[    0.000000] PM: Registered nosave memory: [mem 0x000f0000-0x000fffff]
[    0.000000] PM: Registered nosave memory: [mem 0xdfff0000-0xdfffffff]
[    0.000000] PM: Registered nosave memory: [mem 0xe0000000-0xfebfffff]
[    0.000000] PM: Registered nosave memory: [mem 0xfec00000-0xfec00fff]
[    0.000000] PM: Registered nosave memory: [mem 0xfec01000-0xfedfffff]
[    0.000000] PM: Registered nosave memory: [mem 0xfee00000-0xfee00fff]
[    0.000000] PM: Registered nosave memory: [mem 0xfee01000-0xfffbffff]
[    0.000000] PM: Registered nosave memory: [mem 0xfffc0000-0xffffffff]
[    0.000000] e820: [mem 0xe0000000-0xfebfffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.000000] setup_percpu: NR_CPUS:512 nr_cpumask_bits:512 nr_cpu_ids:4 nr_node_ids:1
[    0.000000] PERCPU: Embedded 34 pages/cpu @ffff88041fc00000 s99608 r8192 d31464 u524288
[    0.000000] PV qspinlock hash table entries: 256 (order: 0, 4096 bytes)
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 4128632
[    0.000000] Policy zone: Normal
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.4.0-139-generic root=LABEL=cloudimg-rootfs ro console=tty1 console=ttyS0
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Memory: 16414216K/16776760K available (8564K kernel code, 1314K rwdata, 4004K rodata, 1528K init, 1316K bss, 362544K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Kernel/User page tables isolation: enabled
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 64.
[    0.000000] 	RCU restricting CPUs from NR_CPUS=512 to nr_cpu_ids=4.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=64, nr_cpu_ids=4
[    0.000000] NR_IRQS:33024 nr_irqs:456 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty1] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] tsc: Detected 3399.996 MHz processor
[    1.002922] Calibrating delay loop (skipped) preset value.. 6799.99 BogoMIPS (lpj=13599984)
[    1.005738] pid_max: default: 32768 minimum: 301
[    1.007222] ACPI: Core revision 20150930
[    1.011919] ACPI: 2 ACPI AML tables successfully acquired and loaded
[    1.013945] Security Framework initialized
[    1.015277] Yama: becoming mindful.
[    1.016497] AppArmor: AppArmor initialized
[    1.021077] Dentry cache hash table entries: 2097152 (order: 12, 16777216 bytes)
[    1.042620] Inode-cache hash table entries: 1048576 (order: 11, 8388608 bytes)
[    1.052829] Mount-cache hash table entries: 32768 (order: 6, 262144 bytes)
[    1.054836] Mountpoint-cache hash table entries: 32768 (order: 6, 262144 bytes)
[    1.058842] Initializing cgroup subsys io
[    1.066609] Initializing cgroup subsys memory
[    1.081272] Initializing cgroup subsys devices
[    1.089402] Initializing cgroup subsys freezer
[    1.110805] Initializing cgroup subsys net_cls
[    1.132260] Initializing cgroup subsys perf_event
[    1.140163] Initializing cgroup subsys net_prio
[    1.141660] Initializing cgroup subsys hugetlb
[    1.143129] Initializing cgroup subsys pids
[    1.145234] mce: CPU supports 0 MCE banks
[    1.146754] Last level iTLB entries: 4KB 64, 2MB 8, 4MB 8
[    1.148493] Last level dTLB entries: 4KB 64, 2MB 0, 4MB 0, 1GB 4
[    1.150590] Spectre V2 : Mitigation: Full generic retpoline
[    1.152378] Spectre V2 : Spectre v2 mitigation: Speculation control IBPB not-supported IBRS not-supported
[    1.154880] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[    1.164902] Speculative Store Bypass: Vulnerable
[    1.169706] Freeing SMP alternatives memory: 32K
[    1.182762] ftrace: allocating 32278 entries in 127 pages
[    1.264489] smpboot: APIC(0) Converting physical 0 to logical package 0
[    1.266614] smpboot: Max logical packages: 1
[    1.268629] x2apic enabled
[    1.270552] Switched APIC routing to physical x2apic.
[    1.275005] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    1.382643] smpboot: CPU0: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (family: 0x6, model: 0x4f, stepping: 0x1)
[    1.393304] Performance Events: unsupported p6 CPU model 79 no PMU driver, software events only.
[    1.396528] KVM setup paravirtual spinlock
[    1.398908] x86: Booting SMP configuration:
[    1.407378] .... node  #0, CPUs:      #1
[    1.415201] kvm-clock: cpu 1, msr 4:1ffe5041, secondary cpu clock
[    1.417208] mce: CPU supports 0 MCE banks
[    1.419982]  #2
[    1.427110] kvm-clock: cpu 2, msr 4:1ffe5081, secondary cpu clock
[    1.429042] mce: CPU supports 0 MCE banks
[    1.432981]  #3
[    1.447536] kvm-clock: cpu 3, msr 4:1ffe50c1, secondary cpu clock
[    1.449577] mce: CPU supports 0 MCE banks
[    1.452365] x86: Booted up 1 node, 4 CPUs
[    1.454661] smpboot: Total of 4 processors activated (27199.96 BogoMIPS)
[    1.458081] devtmpfs: initialized
[    1.474469] evm: security.selinux
[    1.475782] evm: security.SMACK64
[    1.477801] evm: security.SMACK64EXEC
[    1.480928] evm: security.SMACK64TRANSMUTE
[    1.482436] evm: security.SMACK64MMAP
[    1.490994] evm: security.ima
[    1.492550] evm: security.capability
[    1.494309] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    1.498136] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    1.500528] pinctrl core: initialized pinctrl subsystem
[    1.502498] RTC time:  4:16:43, date: 11/18/18
[    1.504249] NET: Registered protocol family 16
[    1.516204] cpuidle: using governor ladder
[    1.528881] cpuidle: using governor menu
[    1.530216] PCCT header not found.
[    1.551326] ACPI: bus type PCI registered
[    1.552651] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    1.560217] PCI: Using configuration type 1 for base access
[    1.586565] ACPI: Added _OSI(Module Device)
[    1.588269] ACPI: Added _OSI(Processor Device)
[    1.590186] ACPI: Added _OSI(3.0 _SCP Extensions)
[    1.592304] ACPI: Added _OSI(Processor Aggregator Device)
[    1.597867] ACPI: Executed 1 blocks of module-level executable AML code
[    1.604734] ACPI: Interpreter enabled
[    1.613035] ACPI: (supports S0 S5)
[    1.627309] ACPI: Using IOAPIC for interrupt routing
[    1.635108] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    1.654444] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    1.657726] acpi PNP0A03:00: _OSC: OS supports [ASPM ClockPM Segments MSI]
[    1.660050] acpi PNP0A03:00: _OSC: not requesting OS control; OS requires [ExtendedConfig ASPM ClockPM MSI]
[    1.664828] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[    1.692176] PCI host bridge to bus 0000:00
[    1.702305] pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7 window]
[    1.712110] pci_bus 0000:00: root bus resource [io  0x0d00-0xffff window]
[    1.714026] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff window]
[    1.723493] pci_bus 0000:00: root bus resource [mem 0xe0000000-0xfdffffff window]
[    1.731810] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.741108] pci 0000:00:01.1: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[    1.749305] pci 0000:00:01.1: legacy IDE quirk: reg 0x14: [io  0x03f6]
[    1.752445] pci 0000:00:01.1: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[    1.754446] pci 0000:00:01.1: legacy IDE quirk: reg 0x1c: [io  0x0376]
[    1.897903] pci 0000:00:07.0: quirk: [io  0x4000-0x403f] claimed by PIIX4 ACPI
[    1.902451] pci 0000:00:07.0: quirk: [io  0x4100-0x410f] claimed by PIIX4 SMB
[    1.952812] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 9 10 *11)
[    1.963496] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 9 *10 11)
[    1.972112] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 *9 10 11)
[    1.982955] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 9 10 *11)
[    1.993560] ACPI: Enabled 2 GPEs in block 00 to 07
[    2.008905] vgaarb: setting as boot device: PCI:0000:00:02.0
[    2.010573] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    2.020082] vgaarb: loaded
[    2.026448] vgaarb: bridge control possible 0000:00:02.0
[    2.028457] SCSI subsystem initialized
[    2.029878] ACPI: bus type USB registered
[    2.031376] usbcore: registered new interface driver usbfs
[    2.033032] usbcore: registered new interface driver hub
[    2.034757] usbcore: registered new device driver usb
[    2.036752] PCI: Using ACPI for IRQ routing
[    2.038512] NetLabel: Initializing
[    2.039828] NetLabel:  domain hash size = 128
[    2.041484] NetLabel:  protocols = UNLABELED CIPSOv4
[    2.044223] NetLabel:  unlabeled traffic allowed by default
[    2.046253] amd_nb: Cannot enumerate AMD northbridges
[    2.048090] clocksource: Switched to clocksource kvm-clock
[    2.065362] AppArmor: AppArmor Filesystem Enabled
[    2.068403] pnp: PnP ACPI init
[  2.077574] pnp: PnP ACPI: found 3 devices
[  2.153463] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[  2.219188] NET: Registered protocol family 2
[    2.282000] TCP established hash table entries: 131072 (order: 8, 1048576 bytes)
[    2.286241] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[  22808TCP: Hash tables configured (establishe 1072 bind 65536)
[    2.602938] UDP hash table entries: 8192 (order: 6, 262144 bytes)
[    2.604991] UDP-Lite hash table entries: 8192 (order: 6, 262144 bytes)
[    2.607063] NET: Registered protocol family 1
[    2.608642] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    2.610481] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    2.612489] Unpacking initramfs...

[    3.028529] Freeing initrd memory: 14792K
[    3.030004] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    3.032014] software IO TLB [mem 0xdbff0000-0xdfff0000] (64MB) mapped at [ffff8800dbff0000-ffff8800dffeffff]
[   3.035415] platform rtc_cmos: registered platform RTC device (no PNP device found)
[    3.069975] Scanning for low memory corruption every 60 seconds

[    3.072471] audit: initializing netlink subsys (disabled)
[    3.074291] audit: type=2000 audit(1542514610.115:1): initialized
[    3.078473] Initialise system trusted keyring
[    3.080273] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    3.084934] zbud: loaded
[    3.086498] VFS: Disk quotas dquot_6.6.0
[    3.087867] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    3.090365] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.092612] fuse init (API version 7.23)
[    3.094299] Key type big_key registered
[    3.095679] Allocating IMA MOK and blacklist keyrings.
[    3.099088] Key type asymmetric registered
[    3.100976] Asymmetric key parser 'x509' registered
[    3.102719] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    3.111486] io scheduler noop registered
[    3.112852] io scheduler deadline registered (default)
[    3.127710] io scheduler cfq registered
[    3.135363] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    3.137214] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    3.139357] ACPI: AC Adapter [AC] (on-line)
[    3.147461] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    3.155541] ACPI: Power Button [PWRF]
[    3.169942] input: Sleep Button as /devices/LNXSYSTM:00/LNXSLPBN:00/input/input1
[    3.178720] ACPI: Sleep Button [SLPF]
[    3.180447] GHES: HEST is not enabled!
[    3.181986] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    3.207347] 00:02: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    3.220574] Linux agpgart interface v0.103
[    3.226499] loop: module loaded
[    3.228781] scsi host0: ata_piix
[    3.230173] scsi host1: ata_piix
[    3.231436] ata1: PATA max UDMA/33 cmd 0x1f0 ctl 0x3f6 bmdma 0xd000 irq 14
[    3.233468] ata2: PATA max UDMA/33 cmd 0x170 ctl 0x376 bmdma 0xd008 irq 15
[    3.235561] libphy: Fixed MDIO Bus: probed
[    3.237022] tun: Universal TUN/TAP device driver, 1.6
[    3.238606] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    3.240580] PPP generic driver version 2.4.2
[    3.242103] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    3.243933] ehci-pci: EHCI PCI platform driver
[    3.251766] ehci-platform: EHCI generic platform driver
[    3.266669] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    3.270391] ohci-pci: OHCI PCI platform driver
[  3280991] ohci-platform: OHCI generic platform driver
[    3.389418] uhci_hcd: USB Universal Host Controller Interface driver
[    3.410697] i8042: PNP: PS/2 Controller [PNP0303:PS2K,PNP0f03:PS2M] at 0x60,0x64 irq 1,12
[    32026serio: i8042 KBD port at 0x60,0x64 irq 1
[    3.585358] serio: i8042 AUX port at 0x60,0x64 irq 12
[    3.587357] mousedev: PS/2 mouse device common for all mice
[    3.589578] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input2
[    3.593053] rtc_cmos rtc_cmos: rtc core: registered rtc_cmos as rtc0
[    3.595010] rtc_cmos rtc_cmos: alarms up to one day, 114 bytes nvram
[    3.596846] i2c /dev entries driver
[    3.598184] device-mapper: uevent: version 1.0.3
[    3.599867] device-mapper: ioctl: 4.34.0-ioctl (2015-10-28) initialised: dm-devel@redhat.com
[    3.602826] ledtrig-cpu: registered to indicate activity on CPUs

[    3.605462] NET: Registered protocol family 10
[    3.608456] NET: Registered protocol family 17
[    3.609910] Key type dns_resolver registered
[    3.618405] registered taskstats version 1
[    3.619766] Loading compiled-in X.509 certificates
[    3.631168] Loaded X.509 cert 'Build time autogenerated kernel key: a88b0f663ecfd40e6a501dee2f0b211d51902e35'
[    3.635666] zswap: loaded using pool lzo/zbud
[    3.639757] Key type trusted registered
[    3.647174] Key type encrypted registered
[    3.648516] AppArmor: AppArmor sha1 policy hashing enabled
[    3.650273] ima: No TPM chip found, activating TPM-bypass!
[    3.651914] ima: Allocated hash algorithm: sha1
[    3.659522] evm: HMAC attrs: 0x1
[    3.673331]   Magic number: 10:524:262
[    3.681026] rtc_cmos rtc_cmos: setting system clock to 2018-11-18 04:16:45 UTC (1542514605)
[    3.684318] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    3.686313] EDD information not available.
[    3.692084] Freeing unused kernel memory: 1528K
[    3.712773] Write protecting the kernel read-only data: 14336k
[    3.722373] Freeing unused kernel memory: 1664K
[    3.724468] Freeing unused kernel memory: 92K
Loading, please wait...
starting version 229
[    3.743848] random: systemd-udevd: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.744681] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.744709] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.759626] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.759691] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.760159] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.760244] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.760329] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.760411] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.760510] random: udevadm: uninitialized urandom read (16 bytes read, 5 bits of entropy available)
[    3.864955] Fusion MPT base driver 3.04.20
[    3.867563] Copyright (c) 1999-2008 LSI Corporation
[    3.883240] Fusion MPT SPI Host driver 3.04.20
[    3.885161] AVX2 version of gcm_enc/dec engaged.
[    3.886716] AES CTR mode by8 optimization enabled
[    3.889641] e1000: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[    3.891855] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    3.895072] mptbase: ioc0: Initiating bringup
[    3.960826] ioc0: LSI53C1030 A0: Capabilities={Initiator}
[    4.032709] tsc: Refined TSC clocksource calibration: 3400.195 MHz
[    4.034512] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x310306e44b4, max_idle_ns: 440795223829 ns
[    4.079571] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
[    4.125973] scsi host2: ioc0: LSI53C1030 A0, FwRev=00000000h, Ports=1, MaxQ=256, IRQ=20
[    4.240773] scsi 2:0:0:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    4.243749] scsi target2:0:0: Beginning Domain Validation
[    4.258536] scsi target2:0:0: Domain Validation skipping write tests
[    4.266736] scsi target2:0:0: Ending Domain Validation
[    4.274402] scsi target2:0:0: asynchronous
[    4.320483] scsi 2:0:1:0: Direct-Access     VBOX     HARDDISK         1.0  PQ: 0 ANSI: 5
[    4.324430] scsi target2:0:1: Beginning Domain Validation
[    4.328290] scsi target2:0:1: Domain Validation skipping write tests
[    4.331253] scsi target2:0:1: Ending Domain Validation
[    4.332955] scsi target2:0:1: asynchronous
[    4.342210] sd 2:0:0:0: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    4.342408] sd 2:0:0:0: Attached scsi generic sg0 type 0
[    4.343186] sd 2:0:1:0: Attached scsi generic sg1 type 0
[    4.343488] sd 2:0:1:0: [sdb] 20480 512-byte logical blocks: (10.5 MB/10.0 MiB)
[    4.343640] sd 2:0:1:0: [sdb] Write Protect is off
[    4.343752] sd 2:0:1:0: [sdb] Incomplete mode parameter data
[    4.343755] sd 2:0:1:0: [sdb] Assuming drive cache: write through
[    4.346080] sd 2:0:1:0: [sdb] Attached SCSI disk
[    4.379021] sd 2:0:0:0: [sda] Write Protect is off
[    4.381186] sd 2:0:0:0: [sda] Incomplete mode parameter data
[    4.383321] sd 2:0:0:0: [sda] Assuming drive cache: write through
[    4.387138]  sda: sda1
[    4.391595] sd 2:0:0:0: [sda] Attached SCSI disk
[    4.684898] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 02:6c:0f:88:42:07
[    4.693918] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[    4.697095] e1000 0000:00:03.0 enp0s3: renamed from eth0
Begin: Loading essential drivers ... [    6.451426] md: linear personality registered for level -1
[    6.456380] md: multipath personality registered for level -4
[    6.461313] md: raid0 personality registered for level 0
[    6.484622] md: raid1 personality registered for level 1
[    6.564398] raid6: sse2x1   gen()  2954 MB/s
[    6.632266] raid6: sse2x1   xor()  1916 MB/s
[    6.700504] raid6: sse2x2   gen()  4957 MB/s
[    6.768327] raid6: sse2x2   xor()  3525 MB/s
[    6.836587] raid6: sse2x4   gen()  7775 MB/s
[    6.920459] raid6: sse2x4   xor()  4611 MB/s
[    6.996527] raid6: avx2x1   gen()  5878 MB/s
[    7.068238] raid6: avx2x2   gen() 11870 MB/s
[    7.136481] raid6: avx2x4   gen() 15307 MB/s
[    7.137975] raid6: using algorithm avx2x4 gen() 15307 MB/s
[    7.146095] raid6: using avx2x2 recovery algorithm
[    7.177140] xor: automatically using best checksumming function:
[    7.216461]    avx       : 18791.000 MB/sec
[    7.219368] async_tx: api initialized (async)
[    7.230029] md: raid6 personality registered for level 6
[    7.251270] md: raid5 personality registered for level 5
[    7.253057] md: raid4 personality registered for level 4
[    7.268865] md: raid10 personality registered for level 10
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... [    7.318661] Btrfs loaded
Scanning for Btrfs filesystems
done.
Warning: fsck not present, so skipping root file system
[    7.361476] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
done.
Begin: Running /scripts/local-bottom ... done.
Begin: Running /scripts/init-bottom ... done.
[    7.505308] systemd[1]: systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
[    7.510861] systemd[1]: Detected virtualization oracle.
[    7.512647] systemd[1]: Detected architecture x86-64.

Welcome to [1mUbuntu 16.04.5 LTS[0m!

[    8.039343] systemd[1]: Set hostname to <ubuntu-xenial>.
[  8064]ysmd]:LitengonounaAudit Socket.
[[0;32m  OK  [0m] Listening on Journal Audit Socket.
[  89272] systemd[1]: Listening on LVM2 metadata daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 metadata daemon socket.
[  9.076461] systemd[1]: Started Trigger resolvconf update for networkd DNS.
[[0;32m  OK  [0m] Started Trigger resolvconf update for networkd DNS.
[    9.164039] systemd[1]: Created slice System Slice.
[[0;32m  OK  [0m] Created slice System Slice.
[    9.180471] systemd[1]: Listening on Journal Soket.
[[0;32m  OK  [0m] Listening on Journal Socket.
[    9.548364] systemd[1]: Starting Uncomplicated firewall...
         Starting Uncomplicated firewall...
[    9.560784] systemd[1]: Starting Nameserver information manager...
         Starting Nameserver information manager...
[    9.599218] systemd[1]: Mounting POSIX Message Queue File System...
         Mounting POSIX Message Queue File System...
[    9.602807] systemd[1]: Reached target Swap.
[[0;32m  OK  [0m] Reached target Swap.
[    9.613012] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[[0;32m  OK  [0m] Listening on /dev/initctl Compatibility Named Pipe.
[    9.630195] systemd[1]: Listening on Journal Socket (/dev/log).
[[0;32m  OK  [0m] Listening on Journal Socket (/dev/log).
[    9.648433] systemd[1]: Listening on udev Kernel Socket.
[[0;32m  OK  [0m] Listening on udev Kernel Socket.
[    9.657877] systemd[1]: Created slice system-serial\x2dgetty.slice.
[[0;32m  OK  [0m] Created slice system-serial\x2dgetty.slice.
[   10.013087] systemd[1]: Starting Set console keymap...
[   10.014837] random: nonblocking pool is initialized
         Starting Set console keymap...
[   10.017048] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[[0;32m  OK  [0m] Started Forward Password Requests to Wall Directory Watch.
[   10.021613] systemd[1]: Reached target User and Group Name Lookups.
[[0;32m  OK  [0m] Reached target User and Group Name Lookups.
[   10.025891] systemd[1]: Listening on LVM2 poll daemon socket.
[[0;32m  OK  [0m] Listening on LVM2 poll daemon socket.
[   10.030314] systemd[1]: Starting Remount Root and Kernel File Systems...
         Starting Remount Root and Kernel File Systems...
[   10.039937] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[   10.047968] EXT4-fs (sda1): re-mounted. Opts: (null)
[[0;32m  OK  [0m] Listening on Device-mapper event daemon FIFOs.
[   10.097688] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
         Starting Monitoring of LVM2 mirrors... dmeventd or progress polling...
[   10.111726] systemd[1]: Reached target System Time Synchronized.
[[0;32m  OK  [0m] Reached target System Time Synchronized.
[   10.117474] systemd[1]: Starting Load Kernel Modules...
         Starting Load Kernel Modules...
[   10.129981] systemd[1]: Mounting Huge Pages File System...
         Mounting Huge Pages File System...
[   10.133609] systemd[1]: Listening on udev Control Socket.
[[0;32m  OK  [0m] Listening on udev Control Socket.
[   10.137532] systemd[1]: Mounting Debug File System...
[   10.146354] Loading iSCSI transport class v2.0-870.
         Mounting Debug File System...
[   10.148481] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[[0;32m  OK  [0m] Set up automount Arbitrary Executab...ats File System Automount Point.
[   10.157232] systemd[1]: Reached target Encrypted Volumes.
[   10.159313] iscsi: registered transport (tcp)
[[0;32m  OK  [0m] Reached target Encrypted Volumes.
[   10.162089] systemd[1]: Starting Create list of required static device nodes for the current kernel...
         Starting Create list of required st... nodes for the current kernel...
[   10.176677] systemd[1]: Listening on Syslog Socket.
[[0;32m  OK  [0m] Listening on Syslog Socket.
[   10.180193] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[   10.188534] systemd[1]: Created slice User and Session Slice.
[[0;32m  OK  [0m] Created slice User and Session Slice.
[   10.194499] systemd[1]: Reached target Slices.
[[0;32m  OK  [0m] Reached target Slices.
[   10.199695] systemd[1]: Mounted Huge Pages File System.
[[0;32m  OK  [0m] Mounted Huge Pages File System.
[   10.224539] systemd[1]: Mounted POSIX Message Queue File System.
[[0;32m  OK  [0m] Mounted POSIX Message Queue File System.
[   10.230154] systemd[1]: Mounted Debug File System.
[   10.239237] iscsi: registered transport (iser)
[[0;32m  OK  [0m] Mounted Debug File System.
[   10.240898] systemd[1]: Started Journal Service.
[[0;32m  OK  [0m] Started Journal Service.
[[0;32m  OK  [0m] Started Uncomplicated firewall.
[[0;32m  OK  [0m] Started Set console keymap.
[[0;32m  OK  [0m] Started Remount Root and Kernel File Systems.
[[0;32m  OK  [0m] Started Load Kernel Modules.
[[0;32m  OK  [0m] Started Create list of required sta...ce nodes for the current kernel.
[[0;32m  OK  [0m] Started Nameserver information manager.
[[0;32m  OK  [0m] Started LVM2 metadata daemon.
         Starting Create Static Device Nodes in /dev...
         Starting Apply Kernel Variables...
         Mounting FUSE Control File System...
         Starting Load/Save Random Seed...
         Starting udev Coldplug all Devices...
         Starting Flush Journal to Persistent Storage...
[[0;32m  OK  [0m] Mounted FUSE Control File System.
[[0;32m  OK  [0m] Started Apply Kernel Variables.
[[0;32m  OK  [0m] Started Create Static Device Nodes in /dev.
[[0;32m  OK  [0m] Started Load/Save Random Seed.
[[0;32m  OK  [0m] Started Flush Journal to Persistent Storage.
         Starting udev Kernel Device Manager...
[[0;32m  OK  [0m] Started udev Coldplug all Devices.
[[0;32m  OK  [0m] Started udev Kernel Device Manager.
[[0;32m  OK  [0m] Started Dispatch Password Requests to Console Directory Watch.
[[0;32m  OK  [0m] Started Monitoring of LVM2 mirrors,...ng dmeventd or progress polling.
[[0;32m  OK  [0m] Reached target Local File Systems (Pre).
         Mounting Mount unit for core, revision 5742...
         Mounting Mount unit for lxd, revision 9550...
         Mounting Mount unit for conjure-up, revision 1031...
[[0;32m  OK  [0m] Reached target Local File Systems.
         Starting Tell Plymouth To Write Out Runtime Data...
         Starting Set console font and keymap...
         Starting LSB: AppArmor initialization...
         Starting Initial cloud-init job (pre-networking)...
         Starting Create Volatile Files and Directories...
[[0;32m  OK  [0m] Mounted Mount unit for core, revision 5742.
[[0;32m  OK  [0m] Mounted Mount unit for conjure-up, revision 1031.
[[0;32m  OK  [0m] Mounted Mount unit for lxd, revision 9550.
[[0;32m  OK  [0m] Started Tell Plymouth To Write Out Runtime Data.
[[0;32m  OK  [0m] Started Create Volatile Files and Directories.
[[0;32m  OK  [0m] Found device /dev/ttyS0.
[[0;32m  OK  [0m] Started LSB: AppArmor initialization.
[[0;32m  OK  [0m] Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
         Starting Update UTMP about System Boot/Shutdown...
[   10.128829] cloud-init[536]: Cloud-init v. 18.4-0ubuntu1~16.04.2 running 'init-local' at Sun, 18 Nov 2018 04:16:53 +0000. Up 10.06 seconds.
[   10.389343] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,331 - util.py[DEBUG]: Cloud-init v. 18.4-0ubuntu1~16.04.2 running 'init-local' at Sun, 18 Nov 2018 04:16:53 +0000. Up 10.06 seconds.
[   10.394702] cloud-init[536]: tee: /var/log/cloud-init-output.log: No space left on device
[   10.590481] [cloud-init[0;1;31mFAILED[0m[536]: ] FALLBACK: 2018-11-18 04:16:53,331 - main.py[DEBUG]: No kernel command line url found.Failed to start Update UTMP about System Boot/Shutdown.

[   10.590832] See 'systemctl status systemd-update-utmp.service' for details.cloud-init
[536]: FALLBACK: 2018-11-18 04:16:53,332 - main.py[DEBUG]: Closing stdin.
[   10.787490] [cloud-init[0;1;33mDEPEND[0m[536]: ] FALLBACK: 2018-11-18 04:16:53,337 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytesDependency failed for Update UTMP about System Runlevel Changes.

[   10.972950] [cloud-init[0;1;31mFAILED[0m[536]: ] FALLBACK: 2018-11-18 04:16:53,338 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 104:4Failed to start Initial cloud-init job (pre-networking).

[   11.073232] See 'systemctl status cloud-init-local.service' for details.cloud-init
[536]: FALLBACK: 2018-11-18 04:16:53,339 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
[[0;32m  OK  [0m] Reached target Network (Pre).
[   11.172578] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,339 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
[   11.176668] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,339 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
[   11.179159] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,339 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
[   11.181591] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,340 - util.py[DEBUG]: Read 7834 bytes from /var/lib/cloud/instance/obj.pkl
[   11.186941] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,346 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
[   11.192958] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,346 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
[   11.195281] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,346 - stages.py[DEBUG]: cache invalid in datasource: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
[   11.197827] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,346 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: cache invalid in datasource: DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
[   11.198274] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,346 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
[   11.198455] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,349 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
[   11.198768] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,350 - __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'ConfigDrive', 'OpenNebula', 'DigitalOcean', 'Azure', 'AltCloud', 'OVF', 'MAAS', 'GCE', 'OpenStack', 'CloudSigma', 'SmartOS', 'Bigstep', 'Scaleway', 'AliYun', 'Ec2', 'CloudStack', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
[   11.199319] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,397 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
[   11.199496] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,397 - util.py[DEBUG]: Read 298 bytes from /etc/os-release
[   11.199665] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,434 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceNoCloud', 'DataSourceConfigDrive', 'DataSourceOpenNebula', 'DataSourceDigitalOcean', 'DataSourceAzure', 'DataSourceOVF', 'DataSourceOpenStackLocal', 'DataSourceCloudSigma', 'DataSourceSmartOS', 'DataSourceScaleway', 'DataSourceEc2Local']
[   11.200008] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,434 - handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
[   11.200364] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,435 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
[   11.200699] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,435 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
[   11.201089] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,435 - util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
[   11.201270] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,438 - util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
[   11.201452] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,440 - util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
[   11.201636] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,442 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
[   11.201830] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,442 - util.py[DEBUG]: Read 153 bytes from /proc/1/environ
[   11.202292] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,443 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
[   11.202369] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,443 - util.py[DEBUG]: Read 929 bytes from /proc/self/status
[   11.202549] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,443 - util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
[   11.202733] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,443 - util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
[   11.203089] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,443 - util.py[DEBUG]: Read 2 bytes from /sys/class/dmi/id/product_serial
[   11.203275] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,444 - util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned 0
[   11.203456] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,444 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
[   11.203637] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,444 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
[   11.204002] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,444 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
[   11.204375] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,444 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
[   11.204561] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,445 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
[   11.204754] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,445 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
[   11.204922] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,445 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
[   11.270467] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,445 - util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
[   11.270803] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,445 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
[   11.271016] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,448 - util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
[   11.271600] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,450 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[   11.271743] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,459 - util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[   11.271924] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,462 - util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
[   11.272322] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,465 - DataSourceNoCloud.py[DEBUG]: Attempting to use data from /dev/sdb
[   11.272527] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,465 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
[   11.272707] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,466 - util.py[DEBUG]: Read 2160 bytes from /proc/mounts
         Starting Raise network interfaces...
[   11.273148] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,466 - util.py[DEBUG]: Fetched {'/dev/sda1': {'fstype': 'ext4', 'opts': 'rw,relatime,data=ordered', 'mountpoint': '/'}, 'hugetlbfs': {'fstype': 'hugetlbfs', 'opts': 'rw,relatime', 'mountpoint': '/dev/hugepages'}, 'mqueue': {'fstype': 'mqueue', 'opts': 'rw,relatime', 'mountpoint': '/dev/mqueue'}, 'sysfs': {'fstype': 'sysfs', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys'}, '/dev/loop2': {'fstype': 'squashfs', 'opts': 'ro,nodev,relatime', 'mountpoint': '/snap/conjure-up/1031'}, 'proc': {'fstype': 'proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/proc'}, 'fusectl': {'fstype': 'fusectl', 'opts': 'rw,relatime', 'mountpoint': '/sys/fs/fuse/connections'}, '/dev/loop1': {'fstype': 'squashfs', 'opts': 'ro,nodev,relatime', 'mountpoint': '/snap/lxd/9550'}, 'securityfs': {'fstype': 'securityfs', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/kernel/security'}, 'devpts': {'fstype': 'devpts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'mountpoint': '/dev/pts'}, 'udev': {'fstype': 'devtmpfs', 'opts': 'rw,nosuid,relatime,size=8207124k,nr_inodes=2051781,mode=755', 'mountpoint': '/dev'}, '/dev/loop0': {'fstype': 'squashfs', 'opts': 'ro,nodev,relatime', 'mountpoint': '/snap/core/5742'}, 'cgroup': {'fstype': 'cgroup', 'opts': 'rw,nosuid,nodev,noexec,relatime,perf_event', 'mountpoint': '/sys/fs/cgroup/perf_event'}, 'debugfs': {'fstype': 'debugfs', 'opts': 'rw,relatime', 'mountpoint': '/sys/kernel/debug'}, 'tmpfs': {'fstype': 'tmpfs', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'mountpoint': '/sys/fs/cgroup'}, 'systemd-1': {'fstype': 'autofs', 'opts': 'rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct', 'mountpoint': '/proc/sys/fs/binfmt_misc'}, 'pstore': {'fstype': 'pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'mountpoint': '/sys/fs/pstore'}} mounts from proc
[[0;32m  OK  [0m] Started ifup for enp0s3.
[   11.369385] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,466 - util.py[DEBUG]: Running command ['mount', '-o', 'ro,sync', '-t', 'auto', '/dev/sdb', '/run/cloud-init/tmp/tmpyebwd7ek'] with allowed return codes [0] (shell=False, capture=True)
[   11.369824] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,480 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpyebwd7ek//user-data (quiet=False)
[   11.370187] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,481 - util.py[DEBUG]: Read 42 bytes from /run/cloud-init/tmp/tmpyebwd7ek//user-data
[   11.370377] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,481 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpyebwd7ek//meta-data (quiet=False)
[   11.370560] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,481 - util.py[DEBUG]: Read 64 bytes from /run/cloud-init/tmp/tmpyebwd7ek//meta-data
[   11.370743] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,482 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpyebwd7ek//vendor-data (quiet=False)
[   11.370942] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,482 - util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpyebwd7ek//network-config (quiet=False)
[[0;32m  OK  [0m] Started Set console font and keymap.
[   11.371115] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,482 - util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpyebwd7ek'] with allowed return codes [0] (shell=False, capture=True)
[   11.416256] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,548 - util.py[DEBUG]: Attempting to load yaml from string of length 64 with allowed root types (<class 'dict'>,)
[   11.421723] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,550 - DataSourceNoCloud.py[DEBUG]: Using data from /dev/sdb
[   11.427171] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,552 - handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: found local data from DataSourceNoCloud
[   11.429874] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,552 - stages.py[INFO]: Loaded datasource DataSourceNoCloud - DataSourceNoCloud [seed=/dev/sdb][dsmode=net]
[   11.438614] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,552 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
[   11.440945] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,552 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
[   11.443080] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,552 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
[   11.453278] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,585 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
[   11.463508] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,585 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
[   11.463898] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,585 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
[[0;32m  OK  [0m] Created slice system-getty.slice.
[   11.464118] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,591 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
[   11.481424] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,591 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
[   11.486102] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,591 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
[   11.492705] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,606 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
[   11.500479] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,606 - util.py[DEBUG]: Read 48 bytes from /run/cloud-init/cloud.cfg
[   11.507224] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,606 - util.py[DEBUG]: Attempting to load yaml from string of length 48 with allowed root types (<class 'dict'>,)
[   11.516171] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,607 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
[   11.518979] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,608 - util.py[DEBUG]: loaded blob returned None, returning default.
[   11.521131] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,609 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
[   11.525520] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,609 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-756b047207935472'
[   11.530940] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,610 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-756b047207935472/datasource (quiet=False)
[   11.538621] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,611 - util.py[DEBUG]: Read 65 bytes from /var/lib/cloud/instances/iid-756b047207935472/datasource
[   11.545954] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,611 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-756b047207935472/datasource - wb: [644] 65 bytes
[   11.551270] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,613 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 65 bytes
[   11.555979] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,614 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
[   11.556428] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,614 - util.py[DEBUG]: Read 21 bytes from /var/lib/cloud/data/instance-id
[   11.556615] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,614 - stages.py[DEBUG]: previous iid found to be iid-756b047207935472
[   11.556805] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,614 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 21 bytes
[   11.556995] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,615 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 21 bytes
[   11.557222] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,616 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 21 bytes
[   11.557395] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,618 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 5737 bytes
[   11.557572] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,619 - main.py[DEBUG]: [local] init will now be targeting instance id: iid-756b047207935472. new=False
[   11.557750] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,619 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
[   11.557921] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,619 - util.py[DEBUG]: Read 3169 bytes from /etc/cloud/cloud.cfg
[   11.558099] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,619 - util.py[DEBUG]: Attempting to load yaml from string of length 3169 with allowed root types (<class 'dict'>,)
[[0;32m  OK  [0m] Started Raise network interfaces.
[   11.558294] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,651 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
[   11.613033] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,651 - util.py[DEBUG]: Read 238 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
[   11.615299] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,652 - util.py[DEBUG]: Attempting to load yaml from string of length 238 with allowed root types (<class 'dict'>,)
[   11.657890] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,656 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
[   11.663052] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,656 - util.py[DEBUG]: Read 2057 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
[   11.669479] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,656 - util.py[DEBUG]: Attempting to load yaml from string of length 2057 with allowed root types (<class 'dict'>,)
[   11.676624] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,667 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
         Starting Initial cloud-init job (metadata service crawler)...
[[0;32m  OK  [0m] Reached target Network.
[   11.683606] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,667 - util.py[DEBUG]: Read 48 bytes from /run/cloud-init/cloud.cfg
[   11.779486] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,667 - util.py[DEBUG]: Attempting to load yaml from string of length 48 with allowed root types (<class 'dict'>,)
[   11.782187] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,668 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
[   11.788809] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,669 - util.py[DEBUG]: loaded blob returned None, returning default.
[   11.791120] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,669 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
[   11.793536] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,669 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/instance/cloud-config.txt
[   11.800169] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,669 - util.py[DEBUG]: Attempting to load yaml from string of length 78 with allowed root types (<class 'dict'>,)
[   11.808329] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,673 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
[   11.839166] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,675 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
[   11.844978] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,675 - util.py[DEBUG]: Read 59 bytes from /var/lib/cloud/data/set-hostname
[   11.856226] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,675 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
[   11.862469] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,677 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/name_assign_type (quiet=False)
[   11.873330] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,677 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/name_assign_type
[   11.879039] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,677 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/carrier (quiet=False)
[   11.881367] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/dormant (quiet=False)
[   11.888452] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
[   11.890808] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
[   11.893028] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[   12.023284] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[   12.025560] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,678 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[   12.032184] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,679 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[   12.034425] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,679 - stages.py[DEBUG]: applying net config names for {'version': 1, 'config': [{'mac_address': '02:6c:0f:88:42:07', 'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'enp0s3'}]}
[   12.041370] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,679 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
[   12.053832] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,679 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
[   12.059471] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,679 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
[   12.061985] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
[   12.068400] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
[   12.070636] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
[   12.072842] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
[   12.080007] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
[   12.085758] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
[   12.091705] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,680 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/addr_assign_type (quiet=False)
[   12.094283] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,681 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enp0s3/addr_assign_type
[   12.096927] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,681 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/uevent (quiet=False)
[   12.104367] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,681 - util.py[DEBUG]: Read 27 bytes from /sys/class/net/enp0s3/uevent
[   12.113466] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,681 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/address (quiet=False)
[   12.120024] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,681 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enp0s3/address
[   12.127697] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/device/device (quiet=False)
[   12.133774] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/enp0s3/device/device
[   12.140405] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
[   12.145928] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
[   12.156962] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Reading from /sys/class/net/enp0s3/operstate (quiet=False)
[   12.159388] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,682 - util.py[DEBUG]: Read 5 bytes from /sys/class/net/enp0s3/operstate
[   12.164782] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,683 - util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
[   12.174858] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,688 - util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
[   12.181075] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,691 - __init__.py[DEBUG]: no work necessary for renaming of [['02:6c:0f:88:42:07', 'enp0s3', 'e1000', '0x100e']]
[   12.188695] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,692 - __init__.py[DEBUG]: Datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not updated for events: System boot
[   12.199872] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,692 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
[   12.202745] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,692 - main.py[DEBUG]: [local] Exiting. datasource DataSourceNoCloud [seed=/dev/sdb][dsmode=net] not in local mode.
[   12.205809] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,693 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
[   12.208018] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,693 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
[   12.210044] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,693 - util.py[DEBUG]: cloud-init mode 'init' took 0.444 seconds (0.45)
[   12.212286] cloud-init[536]: FALLBACK: 2018-11-18 04:16:53,694 - handlers.py[DEBUG]: finish: init-local: FAIL: searching for local datasources
[   12.218602] cloud-init[536]: OSError: [Errno 28] No space left on device
[   12.223597] cloud-init[536]: During handling of the above exception, another exception occurred:
[   12.228755] cloud-init[536]: Traceback (most recent call last):
[   12.235168] cloud-init[536]:   File "/usr/bin/cloud-init", line 9, in <module>
[   12.240269] cloud-init[536]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   12.247338] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   12.253336] cloud-init[536]:     get_uptime=True, func=functor, args=(name, args))
[   12.259774] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   12.265030] cloud-init[536]:     ret = func(*args, **kwargs)
[   12.276538] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 676, in status_wrapper
[   12.278729] cloud-init[536]:     atomic_helper.write_json(status_path, status)
[   12.280339] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   12.289502] cloud-init[536]:     omode="w", mode=mode)
[   12.290815] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[[0;1;31mFAILED[0m] Failed to start Initial cloud-init job (metadata service crawler).
[   12.375241] cloud-init[536]:     raise e
[   12.380237] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   12.380438] cloud-init[536]:     tf.close()
[   12.380635] cloud-init[536]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   12.380825] cloud-init[536]:     self._closer.close()
[   12.381009] cloud-init[536]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   12.381192] cloud-init[536]:     self.file.close()
[   12.381374] cloud-init[536]: OSError: [Errno 28] No space left on device
[   12.381570] cloud-init[536]: Error in sys.excepthook:
[   12.381741] cloud-init[536]: Traceback (most recent call last):
[   12.381922] cloud-init[536]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   12.382108] cloud-init[536]:     pr.write(f)
[   12.382285] cloud-init[536]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[   12.382609] cloud-init[536]:     file.write(v.replace(b'\n', b'\n '))
[   12.382790] cloud-init[536]: OSError: [Errno 28] No space left on device
[   12.382993] cloud-init[536]: During handling of the above exception, another exception occurred:
[   12.383180] cloud-init[536]: Traceback (most recent call last):
[   12.383737] cloud-init[1028]: OSError: [Errno 28] No space left on device
See 'systemctl status cloud-init.service' for details.
[[   12.384248] [0;32m  OK  [0mcloud-init] [1028]: Reached target Cloud-config availability.During handling of the above exception, another exception occurred:

[   12.430160] [cloud-init[0;32m  OK  [0m[1028]: ] Traceback (most recent call last):Reached target System Initialization.

[   12.430695] cloud-init[1028]:   File "/usr/bin/cloud-init", line 9, in <module>
[   12.434029] [cloud-init[0;32m  OK  [0m[1028]: ]     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()Started Daily apt download activities.

[   12.434467] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   12.445547] [cloud-init[0;32m  OK  [0m[1028]: ]     get_uptime=True, func=functor, args=(name, args))Started Daily Cleanup of Temporary Directories.

[   12.445950] [cloud-init[0;32m  OK  [0m[1028]: ]   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_timeListening on UUID daemon activation socket.

[   12.453546] cloud-init[1028]:     ret = func(*args, **kwargs)
[   12.473489] [cloud-init[0;32m  OK  [0m[1028]: ]   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapperListening on Socket unix for snap application lxd.daemon.

         [   12.473923] Starting Socket activation for snappy daemon.cloud-init
[1028]:     atomic_helper.write_json(status_path, status)
[   12.482641] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   12.491008] [cloud-init[0;32m  OK  [0m[1028]: ]     omode="w", mode=mode)Started ACPI Events Check.

[[   12.491437] [0;32m  OK  [0mcloud-init] [1028]: Reached target Paths.  File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file

[   12.502084] [cloud-init[0;32m  OK  [0m[1028]: ]     raise eStarted Daily apt upgrade and clean activities.

[   12.502503] [cloud-init[0;32m  OK  [0m[1028]: ]   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_fileReached target Timers.

[[   12.506801] [0;32m  OK  [0mcloud-init] [1028]: Listening on D-Bus System Message Bus Socket.    tf.close()

[   12.518233] [cloud-init[0;32m  OK  [0m[1028]: ]   File "/usr/lib/python3.5/tempfile.py", line 648, in closeListening on ACPID Listen Socket.

[   12.518668] [cloud-init[0;32m  OK  [0m[1028]: ]     self._closer.close()Reached target Network is Online.

[   12.521072] cloud-init[1028]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   12.556935]          cloud-initStarting iSCSI initiator daemon (iscsid)...[1028]: 
    self.file.close()
[   12.567225] [cloud-init[0;32m  OK  [0m[1028]: ] OSError: [Errno 28] No space left on deviceListening on Socket activation for snappy daemon.

[   12.567650] cloud-init[1028]: Error in sys.excepthook:
[   12.577136] cloud-init[1028]: Traceback (most recent call last):
[   12.578597] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   12.580758] cloud-init[1028]:     pr.write(f)
[   12.582000] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[   12.587302] cloud-init[1028]:     file.write(v.replace(b'\n', b'\n '))
[   12.591625] cloud-init[1028]: OSError: [Errno 28] No space left on device
[   12.593559] cloud-init[1028]: During handling of the above exception, another exception occurred:
[   12.605021] [cloud-init[0;32m  OK  [0m[1028]: ] Traceback (most recent call last):Started iSCSI initiator daemon (iscsid).

[   12.605430] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   12.621789] cloud-init[1028]:     pr.write(f)
[   12.623107] cloud-init[1028]: OSError: [Errno 28] No space left on device
[   12.627988] cloud-init[1028]: Original exception was:
[   12.632664] cloud-init[1028]: OSError: [Errno 28] No space left on device
[   12.634205] cloud-init[1028]: During handling of the above exception, another exception occurred:
[   12.640105]          cloud-initStarting Login to default iSCSI targets...[1028]: 
Traceback (most recent call last):
[   12.646237] [cloud-init[0;32m  OK  [0m[1028]: ]   File "/usr/bin/cloud-init", line 9, in <module>Reached target Sockets.

[   12.646682] [cloud-init[0;32m  OK  [0m[536]: ]   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthookReached target Basic System.

[   12.656581] cloud-init[536]:     pr.write(f)
[   12.660092]          cloud-initStarting System Logging Service...[536]: 
OSError: [Errno 28] No space left on device
[   12.662668] cloud-init         [536]: Starting /etc/rc.local Compatibility...Original exception was:

[   12.666820]          cloud-initStarting LSB: Record successful boot for GRUB...[536]: 
OSError: [Errno 28] No space left on device
[   12.669437]          cloud-initStarting Service for snap application lxd.activate...[536]: 
During handling of the above exception, another exception occurred:
[   12.675053] [cloud-init[0;32m  OK  [0m[536]: ] Traceback (most recent call last):Started Unattended Upgrades Shutdown.

[[0;32m  OK  [0m] Started Deferred execution scheduler.
[   12.675452] cloud-init[536]:   File "/usr/bin/cloud-init", line 9, in <module>
[   12.684263]          cloud-initStarting Virtualbox guest utils...[536]: 
    load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   12.693749]          cloud-initStarting Login Service...[536]: 
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   12.700656] [cloud-init[0;32m  OK  [0m[536]: ]     get_uptime=True, func=functor, args=(name, args))Started D-Bus System Message Bus.

[   12.701072] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   12.705179] cloud-init[536]:     ret = func(*args, **kwargs)
[   12.708945] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 676, in status_wrapper
[   12.711140] cloud-init[536]:     atomic_helper.write_json(status_path, status)
[   12.716119] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   12.723465] cloud-init[536]:     omode="w", mode=mode)
[   12.724971] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   12.730899] cloud-init[536]:     raise e
[   12.734208] cloud-init[536]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[[0;32m  OK  [0m] Started Regular background program processing daemon.[   12.748443] 
cloud-init[536]:     tf.close()
[   12.750542] [cloud-init[0;32m  OK  [0m[536]: ]   File "/usr/lib/python3.5/tempfile.py", line 648, in closeStarted ACPI event daemon.

[   12.750996] cloud-init[536]:     self._closer.close()
[   12.756856]          cloud-initStarting Snappy daemon...[536]: 
  File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   12.762275]          cloud-initStarting Accounts Service...[536]: 
    self.file.close()
[   12.764121]          cloud-initStarting LSB: MD monitoring daemon...[536]: 
OSError: [Errno 28] No space left on device
[   12.766715] cloud-init[1028]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   12.769095]          cloud-initStarting OpenBSD Secure Shell server...[1028]: 
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   12.771749] cloud-init[1028]:     get_uptime=True, func=functor, args=(name, args))
[[0;32m  OK  [0m] Started System Logging Service.[   12.772255] 
cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   12.775498] cloud-init[1028]:     ret = func(*args, **kwargs)
[   12.775982] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[[0;32m  OK  [0m] Started /etc/rc.local Compatibility.
[   12.776216] cloud-init[1028]:     atomic_helper.write_json(status_path, status)
[[   12.783160] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   12.783396] cloud-init[1028]:     omode="w", mode=mode)
[   12.783610] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   12.783797] cloud-init[1028]:     raise e
[   12.783976] cloud-init[1028]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   12.784367] cloud-init[1028]:     tf.close()
[   12.784543] cloud-init[1028]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   12.784722] cloud-init[1028]:     self._closer.close()
[   12.784909] cloud-init[1028]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   12.785093] cloud-init[1028]:     self.file.close()
[   12.785290] cloud-init[1028]: OSError: [Errno 28] No space left on device
[0;1;31mFAILED[0m] Failed to start Service for snap application lxd.activate.
See 'systemctl status snap.lxd.activate.service' for details.
[[0;32m  OK  [0m] Started OpenBSD Secure Shell server.
[[0;32m  OK  [0m] Started Login to default iSCSI targets.
[[0;32m  OK  [0m] Started LSB: Record successful boot for GRUB.
[[0;32m  OK  [0m] Started LSB: MD monitoring daemon.
[[0;32m  OK  [0m] Started Login Service.
[[0;32m  OK  [0m] Started Virtualbox guest utils.
         Starting Authenticate and Authorize Users to Run Privileged Tasks...
[[0;32m  OK  [0m] Reached target Remote File Systems (Pre).
[[0;32m  OK  [0m] Reached target Remote File Systems.
         Starting LSB: daemon to balance interrupts for SMP systems...
         Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...
         Starting LSB: automatic crash report generation...
         Starting Permit User Sessions...
[[0;32m  OK  [0m] Started Permit User Sessions.
[[0;32m  OK  [0m] Started Authenticate and Authorize Users to Run Privileged Tasks.
[[0;32m  OK  [0m] Started Accounts Service.
[[0;32m  OK  [0m] Started LSB: daemon to balance interrupts for SMP systems.
[[0;32m  OK  [0m] Started LSB: Set the CPU Frequency Scaling governor to "ondemand".
         Starting Terminate Plymouth Boot Screen...
         Starting Hold until boot process finishes up...
[[0;32m  OK  [0m] Started LSB: automatic crash report generation.
[[0;32m  OK  [0m] Started Hold until boot process finishes up.
[[0;32m  OK  [0m] Started Terminate Plymouth Boot Screen.
[[0;32m  OK  [0m] Started Getty on tty1.
         Starting Set console scheme...
[[0;32m  OK  [0m] Started Serial Getty on ttyS0.
[[0;32m  OK  [0m] Reached target Login Prompts.
[[0;32m  OK  [0m] Started Set console scheme.
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
         Starting Wait until snapd is fully seeded...
[[0;32m  OK  [0m] Stopped Snappy daemon.
         Starting Snappy daemon...
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
[[0;32m  OK  [0m] Stopped Snappy daemon.
         Starting Snappy daemon...
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
[[0;32m  OK  [0m] Stopped Snappy daemon.
         Starting Snappy daemon...
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
[[0;32m  OK  [0m] Stopped Snappy daemon.
         Starting Snappy daemon...
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
[[0;32m  OK  [0m] Stopped Snappy daemon.
[[0;1;31mFAILED[0m] Failed to start Snappy daemon.
See 'systemctl status snapd.service' for details.
[[0;32m  OK  [0m] Created slice User Slice of vagrant.
[[0;32m  OK  [0m] Started Session 1 of user vagrant.
         Starting User Manager for UID 1000...
[[0;32m  OK  [0m] Started User Manager for UID 1000.

Ubuntu 16.04.5 LTS ubuntu-xenial ttyS0

ubuntu-xenial login: [   19.558264] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   19.558595] cloud-init[1369]: During handling of the above exception, another exception occurred:
[   19.559323] cloud-init[1369]: Traceback (most recent call last):
[   19.559914] cloud-init[1369]:   File "/usr/bin/cloud-init", line 9, in <module>
[   19.561021] cloud-init[1369]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   19.561562] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   19.561809] cloud-init[1369]:     get_uptime=True, func=functor, args=(name, args))
[   19.562018] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   19.562245] cloud-init[1369]:     ret = func(*args, **kwargs)
[   19.562454] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[   19.562664] cloud-init[1369]:     atomic_helper.write_json(status_path, status)
[   19.562872] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   19.563100] cloud-init[1369]:     omode="w", mode=mode)
[   19.563310] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   19.563523] cloud-init[1369]:     raise e
[   19.563769] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   19.563979] cloud-init[1369]:     tf.close()
[   19.564228] cloud-init[1369]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   19.564437] cloud-init[1369]:     self._closer.close()
[   19.564645] cloud-init[1369]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   19.564854] cloud-init[1369]:     self.file.close()
[   19.565084] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   19.565294] cloud-init[1369]: Error in sys.excepthook:
[   19.565504] cloud-init[1369]: Traceback (most recent call last):
[   19.565752] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   19.565979] cloud-init[1369]:     pr.write(f)
[   19.566189] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[   19.566402] cloud-init[1369]:     file.write(v.replace(b'\n', b'\n '))
[   19.566611] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   19.566820] cloud-init[1369]: During handling of the above exception, another exception occurred:
[   19.567046] cloud-init[1369]: Traceback (most recent call last):
[   19.567257] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   19.567468] cloud-init[1369]:     pr.write(f)
[   19.567715] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   19.567941] cloud-init[1369]: Original exception was:
[   19.568267] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   19.568526] cloud-init[1369]: During handling of the above exception, another exception occurred:
[   19.568737] cloud-init[1369]: Traceback (most recent call last):
[   19.568962] cloud-init[1369]:   File "/usr/bin/cloud-init", line 9, in <module>
[   19.569184] cloud-init[1369]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   19.569400] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   19.569644] cloud-init[1369]:     get_uptime=True, func=functor, args=(name, args))
[   19.569882] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   19.570096] cloud-init[1369]:     ret = func(*args, **kwargs)
[   19.570306] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[   19.570516] cloud-init[1369]:     atomic_helper.write_json(status_path, status)
[   19.570726] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   19.570981] cloud-init[1369]:     omode="w", mode=mode)
[   19.784902] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   19.785390] cloud-init[1369]:     raise e
[   19.786499] cloud-init[1369]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   19.787038] cloud-init[1369]:     tf.close()
[   19.787599] cloud-init[1369]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   19.788298] cloud-init[1369]:     self._closer.close()
[   19.788578] cloud-init[1369]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   19.788812] cloud-init[1369]:     self.file.close()
[   19.789039] cloud-init[1369]: OSError: [Errno 28] No space left on device
[   20.438918] cloud-init[1405]: OSError: [Errno 28] No space left on device
[   20.440183] cloud-init[1405]: During handling of the above exception, another exception occurred:
[   20.440831] cloud-init[1405]: Traceback (most recent call last):
[   20.441459] cloud-init[1405]:   File "/usr/bin/cloud-init", line 9, in <module>
[   20.442043] cloud-init[1405]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   20.442664] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   20.443248] cloud-init[1405]:     get_uptime=True, func=functor, args=(name, args))
[   20.443882] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   20.445548] cloud-init[1405]:     ret = func(*args, **kwargs)
[   20.446675] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[   20.448337] cloud-init[1405]:     atomic_helper.write_json(status_path, status)
[   20.450362] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   20.452286] cloud-init[1405]:     omode="w", mode=mode)
[   20.454597] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   20.456585] cloud-init[1405]:     raise e
[   20.457619] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   20.458697] cloud-init[1405]:     tf.close()
[   20.459765] cloud-init[1405]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   20.461433] cloud-init[1405]:     self._closer.close()
[   20.462509] cloud-init[1405]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   20.463130] cloud-init[1405]:     self.file.close()
[   20.463707] cloud-init[1405]: OSError: [Errno 28] No space left on device
[   20.465580] cloud-init[1405]: Error in sys.excepthook:
[   20.466370] cloud-init[1405]: Traceback (most recent call last):
[   20.467003] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   20.467591] cloud-init[1405]:     pr.write(f)
[   20.468290] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
[   20.468917] cloud-init[1405]:     file.write(v.replace(b'\n', b'\n '))
[   20.470817] cloud-init[1405]: OSError: [Errno 28] No space left on device
[   20.471392] cloud-init[1405]: During handling of the above exception, another exception occurred:
[   20.471930] cloud-init[1405]: Traceback (most recent call last):
[   20.473049] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
[   20.473591] cloud-init[1405]:     pr.write(f)
[   20.474134] cloud-init[1405]: OSError: [Errno 28] No space left on device
[   20.474346] cloud-init[1405]: Original exception was:
[   20.474573] cloud-init[1405]: OSError: [Errno 28] No space left on device
[   20.474785] cloud-init[1405]: During handling of the above exception, another exception occurred:
[   20.474995] cloud-init[1405]: Traceback (most recent call last):
[   20.475204] cloud-init[1405]:   File "/usr/bin/cloud-init", line 9, in <module>
[   20.475922] cloud-init[1405]:     load_entry_point('cloud-init==18.4', 'console_scripts', 'cloud-init')()
[   20.476502] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 904, in main
[   20.476715] cloud-init[1405]:     get_uptime=True, func=functor, args=(name, args))
[   20.476926] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2514, in log_time
[   20.477137] cloud-init[1405]:     ret = func(*args, **kwargs)
[   20.477348] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[   20.477577] cloud-init[1405]:     atomic_helper.write_json(status_path, status)
[   20.478179] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 40, in write_json
[   20.478760] cloud-init[1405]:     omode="w", mode=mode)
[   20.479294] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 33, in write_file
[   20.479523] cloud-init[1405]:     raise e
[   20.479733] cloud-init[1405]:   File "/usr/lib/python3/dist-packages/cloudinit/atomic_helper.py", line 27, in write_file
[   20.479943] cloud-init[1405]:     tf.close()
[   20.480212] cloud-init[1405]:   File "/usr/lib/python3.5/tempfile.py", line 648, in close
[   20.480960] cloud-init[1405]:     self._closer.close()
[   20.481511] cloud-init[1405]:   File "/usr/lib/python3.5/tempfile.py", line 582, in close
[   20.481721] cloud-init[1405]:     self.file.close()
[   20.481930] cloud-init[1405]: OSError: [Errno 28] No space left on device
